In [4]:
#sum of 2 digit 
firstNum = 11
secondNum = 22
sum = firstNum + secondNum
print(sum)



33


In [1]:
# subtract of 2 digits
firstNum = 5
secondNum = 1
diff = firstNum - secondNum
print (diff) 

4


In [4]:
import numpy as np
arr= np.array([10,20,30,40,50])
print([arr])
arr=2*arr
print([arr])
arr=np.arange(0,21,2)
print([arr])
arr2=np.random.randint(1,100,(4,3))
print([arr2])

[array([10, 20, 30, 40, 50])]
[array([ 20,  40,  60,  80, 100])]
[array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])]
[array([[30, 41, 37],
       [31, 49,  2],
       [44,  6, 93],
       [74, 18, 97]], dtype=int32)]


In [5]:
rows = 5

for i in range(1, rows + 1):
    print("*" * i)


*
**
***
****
*****


In [1]:
rows = 5

for i in range(rows, 0, -1):
    print("*" * i)


*****
****
***
**
*


In [2]:
rows = 5

for i in range(1, rows + 1):
    print(" " * (rows - i) + "* " * i)


    * 
   * * 
  * * * 
 * * * * 
* * * * * 


In [3]:
rows = 5

for i in range(1, rows + 1):
    for j in range(1, i + 1):
        print(j, end=" ")
    print()


1 
1 2 
1 2 3 
1 2 3 4 
1 2 3 4 5 


In [4]:
rows = 5
num = 1

for i in range(1, rows + 1):
    for j in range(i):
        print(num, end=" ")
        num += 1
    print()


1 
2 3 
4 5 6 
7 8 9 10 
11 12 13 14 15 


In [2]:
n = 5
alph = 65
for i in range(0, n):
    print(" " * (n-i), end=" ")
    for j in range(0, i+1):
        print(chr(alph), end=" ")
        alph += 1
    alph = 65
    print()

      A 
     A B 
    A B C 
   A B C D 
  A B C D E 


In [3]:
def print_hollow_inverted_half_pyramid(rows):
    for i in range(rows, 0, -1):
        for j in range(rows - i):
            print(" ", end="")
        for j in range(i):
            if j == 0 or j == i - 1 or i == rows:
                print("*", end="")
            else:
                print(" ", end="")
        print()

# Example usage
num_rows = 5
print("Hollow Inverted Half Pyramid:")
print_hollow_inverted_half_pyramid(num_rows)

Hollow Inverted Half Pyramid:
*****
 *  *
  * *
   **
    *


In [6]:
import numpy as np
arr_2d = np.array(([2,4,6],[12,16,18],[32,38,44]))
arr_2d

array([[ 2,  4,  6],
       [12, 16, 18],
       [32, 38, 44]])

In [8]:
arr2=np.random.randint(1,100,(4,3))
print([arr2])

[array([[94, 24, 11],
       [97,  2, 15],
       [22, 27,  2],
       [85, 21, 17]], dtype=int32)]


In [9]:
arr2+arr2

array([[188,  48,  22],
       [194,   4,  30],
       [ 44,  54,   4],
       [170,  42,  34]], dtype=int32)

In [10]:
arr2-arr2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)